### ISSUE TITLE
Clang support

### ISSUE THREAD

**Issue by nicdumz** [wichtounet/budgetwarrior#28]
Howdy,

Just dropping this here, I imagine this is possibly low priority and I understand ;-)

* Because of your use of `views::as_rvalue` and `fold`, both of which are not supported by Clang, budgetwarrior is currently gcc-only.
* make-utils could probably use a bit of love, e.g. [`use_cpp23`](https://github.com/wichtounet/make-utils/tree/f9d90aa1229754782199756598539363c65e6d2d) definitely does not work for clang, which expects `-std=c++2b` for 23.
* If we wanted to add / keep support, I suppose it would make sense to add a workflow testing builds on clang too.

For now I'm fine just not caring / using published Docker images.

Getting rid of folds is feasible with a bit more verbosity and I had a bit of fun with this already. I'm not sure what to do with `as_rvalue`, I don't have familiarity with this idiom yet :-)

Cheers!

**Comment by wichtounet** [comment]
Hi 

Yes, I am aware of that. I am currently using this project has a sandbox to play with C++23, and there is currently no version of clang/libc++ that supports all the features

As you said, it would be fairly reasonable to make it work for clang, but libc++ is missing tons of features. 

fold_left is really not too difficult to implement and as_rvalue can be implemented as a transform view I believe. 

I will keep this open and try to do this in the coming weeks. I want to get back clang support on Linux because I want to integrate clang-tidy later on.

**Comment by nicdumz** [comment]
Thanks! And please, no urgency in this request. I'm good for now with
prebuilt docker images :-)

**Comment by wichtounet** [comment]
With the latest changes to master, clang should be supported now 👍 

I have added a GH workflow to test with clang as well.
